### ISSUE TITLE
Move to Remark

### ISSUE THREAD

**Issue by zacanger** [entropic-dev/entropic#214] opened 2019-06-08 17:17 UTC
`markdown` is unmaintained.

Discussion [here](https://github.com/entropic-dev/entropic/pull/135#discussion_r291796711).

Some popular options:

* `marky-markdown`
* `remark` and its ecosystem
* `markdown-it` and its ecosystem (`marky-markdown` is built on top of `markdown-it`)
* `showdown`
* `marked`

**EDIT**

[Remark it is!](https://github.com/entropic-dev/entropic/issues/214#issuecomment-500975986)
[Docs](https://unified.js.org/) for whoever picks this up.

**Comment by aredridel** [comment] 2019-06-08 17:40
As a counterpoint, the remark library and associated ecosystem is quite rich.

**Comment by zacanger** [comment] 2019-06-08 18:12
I don't have a strong opinion about what we move to (as long as it's not abandoned), just mentioned `marky-markdown` because Chris mentioned it.

**Comment by avickers** [comment] 2019-06-09 02:26
[This could be worth a look.](https://commonmark.org/)

There's no official specification.  An implementation that is committed to tracking Github's syntax, like marky-markdown, might be desirable, if its sole purpose is to render markdown created on Github.

**Comment by zeke** [comment] 2019-06-09 04:53
As the original author of `marky-markdown`, I wouldn't suggest it for use in entropic. It was designed specifically for the needs of the npmjs.com website (in 2015), so it has a lot of extra bells and whistles that don't apply to most projects. It also has a dependency on the `oniguruma` package, which is a native module that has proved problematic over the years, and a difficult upstream dependency to maintain.

I would echo @aredridel's suggestion to use [`remark`](https://remark.js.org/). It's fast, CommonMark compliant, has a nice plugin system, and its original author @wooorm has created [`unified`](https://opencollective.com/unified#about), an umbrella organization to fund and sustain the project's development.

For electronjs.org and docs.github.com, we maintain a module called [`hubdown`](https://github.com/electron/hubdown) which includes `remark` with a handful of plugins for doing GitHubby stuff like syntax highlight and auto-linked headings.

**Comment by revin** [comment] 2019-06-11 18:35
I helped maintain `marky-markdown` for a while, and I'd echo @zeke here. We worked to generalize it so it wasn't so npmjs.com-specific, and definitely improved on the state of things we had when we began that effort. However, the other valuable stuff `marky-markdown` provided has almost all become obsolete over time because while we were tracking quirks of GitHub-Flavored Markdown that didn't match CommonMark, GFM eventually moved to become close enough to CommonMark that we mostly didn't need the special handling anymore.

**Comment by chrisdickinson** [comment] 2019-06-11 18:53
I'm sold! Let's plan on going with remark.

**Comment by zacanger** [comment] 2019-06-12 01:44
@ceejbot @chrisdickinson would this make for a "good first issue"?

**Comment by enykeev** [comment] 2019-06-12 07:50
> @ceejbot @chrisdickinson would this make for a "good first issue"?

https://github.com/entropic-dev/entropic/search?q=markdown&unscoped_q=markdown

**Comment by varjmes** [comment] 2019-06-12 10:33
> @ceejbot @chrisdickinson would this make for a "good first issue"?

I think this is a perfect first issue :)

**Closed** 2019-09-19 16:14 UTC
