### ISSUE TITLE
bug: getaddrinfo ENOTFOUND registry.entropic.dev registry.entropic.dev:443

### ISSUE THREAD

**Issue by niklabh** [entropic-dev/entropic#273] opened 2019-06-14 16:15 UTC
# Is this a feature request or a bug?
bug
# Expected behavior:
cli commands works
# Actual behavior:
FetchError: request to https://registry.entropic.dev/ping failed, reason: getaddrinfo ENOTFOUND registry.entropic.dev registry.entropic.dev:443

# Steps to replicate:
run ./cli/lib/main.js ping

removing family:6 from cli/lib/fetch.js works

# Environment info (where relevant)
node version v10.16.0
Linux ubuntu 5.0.0-16-generic
ds version master

**Comment by zacanger** [comment] 2019-06-14 16:27
Duplicate of #228 
See also #183, #177, #229

**Closed** 2019-06-14 19:44 UTC
